---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - "eval $(curl https://travis-perl.github.io/init) --auto"
language: perl
matrix:
  include:
    env: COVERAGE=1
    perl: "5.30"
notifications:
  email:
    if: repo = "tokuhirom/OrePAN2"
    on_failure: always
    on_success: always
    recipients:
      - olaf@wundersolutions.com
